[build]
  dockerfile = "Dockerfile"

[[services]]
  name = "web"
  startCommand = "sh start.sh"
  healthcheckPath = "/health"
  restartPolicyType = "on-failure"

  [[services.volumes]]
    mountPath = "/data"
    name = "shared-data"

[[services]]
  name = "worker"
  startCommand = "celery -A app.celery_worker.celery worker --loglevel=info --concurrency=1 -P prefork"
  restartPolicyType = "on-failure"

  [[services.volumes]]
    mountPath = "/data"
    name = "shared-data"

[[services]]
  name = "beat"
  startCommand = "celery -A app.celery_worker.celery beat --loglevel=info"
  restartPolicyType = "on-failure"
