"""Add User model with created_at column

Revision ID: 8ac4fd786e58
Revises: 8bec7bf3f7e1
Create Date: 2025-08-25 01:06:03.366209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ac4fd786e58'
down_revision = '8bec7bf3f7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.alter_column('start_char',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_char',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('chunks_user_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('files_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('size')
        batch_op.drop_column('path')
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        # Keep the existing password_hash length to avoid data truncation
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('files_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('file_metadata')

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('chunks_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('end_char',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_char',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
