"""Add path and size columns to File model

Revision ID: 9f5521d4f87d
Revises: 8ac4fd786e58
Create Date: 2025-08-25 01:15:23.535792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5521d4f87d'
down_revision = '8ac4fd786e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('files', sa.Column('path', sa.String(length=500), nullable=True))
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE files SET path = 'unknown' WHERE path IS NULL")
    op.execute("UPDATE files SET size = 0 WHERE size IS NULL")
    
    # Now make columns non-nullable
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('path', nullable=False)
        batch_op.alter_column('size', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('size')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
