"""Add processed column to files

Revision ID: ba44f4dbb22d
Revises: 9f5521d4f87d
Create Date: 2025-09-04 22:42:56.488997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba44f4dbb22d'
down_revision = '9f5521d4f87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('processed')

    # ### end Alembic commands ###
