"""Add pilot fields

Revision ID: d5934fa0ff7d
Revises: ba44f4dbb22d
Create Date: 2025-09-25 20:29:20.866295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5934fa0ff7d'
down_revision = 'ba44f4dbb22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pilot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pilot_purchased_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pilot_purchased_at')
        batch_op.drop_column('is_pilot')

    # ### end Alembic commands ###
